### PR TITLE
Add option to export is_missing and is_illegible value flags

### PR DESCRIPTION
**Pull request by jimsafley**
Adds a dataset option to flag values as missing and/or illegible in the exported dataset. This will add two columns to the right of every value: is_missing and is_illegible. The default behavior is to omit the is_missing and is_illegible columns.

Note that this requires a migration, so it may be best to test the other PRs first.

### CODE REVIEW

**Comment by mebrett** [comment]
The migration means erasing from the database all of the work that has already been done on a project. Would there be a way to rebuild all of that information, through some sort of direct work in the MySQL database? Not something to build into the code but something we could document?

The original issue was created with Death by Numbers in mind, and we've already got a lot of transcription work done on that project, with more in-progress. We don't want to lose what we have. In addition, it would be good to be able to write up how to restore projects/datasets through database work for any future updates or exciting disasters that people might experience.

**Comment by jimsafley** [comment]
The migration should preserve all existing work. Are you seeing something different?

**Comment by mebrett** [comment]
Can you set out the precise steps for migration so I can be sure I'm not mucking it up (and so that we can put it in the docs)?

**Comment by jimsafley** [comment]
Check out the [export-missing-illegible](https://github.com/jimsafley/Datascribe-module/tree/export-missing-illegible) branch, navigate to the admin Modules page, and click the "Upgrade" button next to DataScribe.

**Comment by mebrett** [comment]
That worked very well, thank you.

**Pull request merged**
